name: Test

permissions:
  contents: read

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: 'Test'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v5

      - name: Install bats-core
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo npm install -g bats
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install bats-core
          fi

      - name: Run tests
        run: bats tests/
